management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: Monetiza
    description: Monetiza
    author: Audrin
    version: '@project.version@'
spring:
  profiles:
    active: dev