spring:
  datasource:
    driverClassName: org.postgresql.Driver 
    url: jdbc:postgresql://localhost:5432/dbzinho
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    generate-dll: true
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update

api:
  security:
    token:
      secret: my-secret-key